FROM sickcodes/docker-osx:latest

# Install brew
RUN bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
ENV PATH=$PATH:/home/linuxbrew/.linuxbrew/bin
# RUN sudo pacman -S base-devel
RUN brew install gcc

# Install cmake
RUN brew install cmake

COPY Asset/ /app/Asset/
COPY include/ /app/include/
COPY lib/ /app/lib/
COPY src/ /app/src/
COPY CMakeLists.txt /app/

WORKDIR /app/build
RUN sudo cmake ..
RUN sudo make
WORKDIR /app

CMD sleep infinity