FROM epitechcontent/epitest-docker:devel

COPY Asset/ /app/Asset/
COPY include/ /app/include/
COPY lib/ /app/lib/
COPY src/ /app/src/
COPY CMakeLists.txt /app/

WORKDIR /app/build
RUN cmake ..
RUN make
WORKDIR /app

CMD sleep infinity